config/routes.rb
Rails.application.routes.draw do

  get "users/login", to: "users#login", as: "login"
  post "users/login", to: "users#create_login_session", as: "create_login_session"
  delete "users/logout", to: "users#logout", as: "logout"
  

  get '/search', to: 'origamis#search', as: 'origamis_search'
  get '/results', to: 'origamis#results', as: 'origamis_search_results'

  post 'origamis/:id/add_to_basket', to: 'users#add_to_basket', as: 'add_to_basket'
  delete 'origamis/:id/delete_from_basket', to: 'users#delete_from_basket', as: 'delete_from_basket'

  get "/my_basket", to: "baskets#my_basket", as: "my_basket"

  resources :posts, except: [:destroy]
  resources :baskets, only: [:show]
  resources :users, except: [:destroy]
  resources :origamis, only: [:index, :show]

  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
    belongs_to :user
    belongs_to :origami




end

app/models/origami.rb
class Origami < ApplicationRecord
    has_many :baskets
    has_many :basket_users, through: :baskets, source: :user

    has_many :posts
    has_many :post_users, through: :posts, source: :user


    def self.search(params)
        Origami.where(params)
    end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :origami

    validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :baskets
    has_many :basket_origamis, through: :baskets, source: :origami

    has_many :posts
    has_many :post_origamis, through: :posts, source: :origami
   
    validates :username, :name, :bio, presence: true

    validates :username, uniqueness: true

    has_secure_password

    def add_to_basket(origami)
        self.basket_origamis << origami
    end


    def delete_from_basket(origami)
        self.basket_origamis.delete(origami)
    end

    def get_reccommended_origami
        likeness_hash = {}
        in_basket = self.basket_origamis
        origamis_not_in_basket = Origami.all.reject{|origami| in_basket.include?(origami)}

        origamis_not_in_basket.each do |origami|
            likeness = 0;
            in_basket.each do |basket_origami|
                if (origami.category == basket_origami.category)
                    likeness += 1
                end 
                if (origami.style == basket_origami.style)
                    likeness += 1
                end 
                if (origami.difficulty == basket_origami.difficulty)
                    likeness += 1
                end
                likeness_hash[origami] = likeness
            end
        end
        likeness_hash.max_by{|origami, likeness| likeness}[0]

    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :current_user
    # before_action :authorize
  
  
    private 
    
    def current_user
      @logged_in_user = User.find_by(id: session[:user_id]) 
    end 
  
    # def authorize
    #   if @logged_in_user 
    #     #do the normal thing
    #   else
    #     flash[:errors] = ["you need to be logged in to preform that action"] 
  
    #     redirect_to login_path
    #   end 
    # end 
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController


    def my_basket
        @basket = @logged_in_user.basket_origamis
        if @basket.size > 0 
            @recommended = @logged_in_user.get_reccommended_origami
        end

    end


end

app/controllers/origamis_controller.rb
class OrigamisController < ApplicationController

def index
    @origamis = Origami.all
    
end

def show
    @origami = Origami.find(params[:id])
end

def search
    @origami_titles = Origami.all.map{|origami| origami.title}
    @origami_categories = Origami.distinct.pluck(:category)
    @origami_difficulties = [1, 2, 3, 4, 5]


    render :search
end

def results
    search_terms = search_params.reject!{|search_key, search_value| search_value.empty?}
    @origamis = Origami.search(search_terms)


    render :index
end

private


def search_params
    params.permit(:title, :category, :difficulty)
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index
    @posts = Post.all
    end

    def show
    @post = Post.find(params[:id])
    end

    def new
    @post = Post.new
    @users = User.all
    @origamis = Origami.all

    end

    def create
    @post = Post.create(post_params)

    if @post.valid?
        redirect_to post_path(@post.id)
    else
        flash[:errors] = @post.errors.full_messages
        
        redirect_to new_post_path
    end

    end

    def edit
    @post = Post.find(params[:id])

    end

    def update
    @post.update(post_params)

    redirect_to post_path(@post.id)

    end

    private

    def post_params
        params.require(:post).permit(:user_id, :origami_id, :content, :title)
    end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController



    #-------------READ-------------#
    
    def show
        @user = User.find(params[:id])
        @posts = @user.posts
        @basket = @user.basket_origamis
    end

    #-------------CREATE-------------#

    def new
        @user = User.new
    end

    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id
            redirect_to user_path(user.id)
        else
            flash[:errors] = user.errors.full_messages
            redirect_to new_user_path
        end
    end

    #-------------LOGIN-------------#

    def login

        render :login
    end

    def create_login_session
        user = User.find_by(username: params[:session][:username])
        
        if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id 
          redirect_to user_path(user.id)  
        else 
          flash[:errors] = ["username or password did not match"]
          redirect_to login_path
        end
    end

    def logout
        session[:user_id] = nil

        redirect_to origamis_path
    end



    #-------------ADD-TO-BASKET-------------#

    def add_to_basket
        origami = Origami.find(params[:origami_id])
        
        @logged_in_user.add_to_basket(origami)

        redirect_to my_basket_path
    end


    #-------------DELETE-FROM-BASKET-------------#

    def delete_from_basket
        origami = Origami.find(params[:origami_id])
        
        @logged_in_user.delete_from_basket(origami)

        redirect_to my_basket_path
    end

    #-------------STRONG-PARAMS-------------#

    private

    def user_params
        params.require(:user).permit(:username, :password, :name, :bio)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/origamis_helper.rb
module OrigamisHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/baskets/my_basket.html.erb
<div class="basket-show-container">
    <div class="header-container">
        <h2> ▧ My Basket ▨ </h2>
    </div>

    <div class="basket-info-container">
        <%if (@basket.size > 0)%>
            <%@basket.each do |origami|%>
                <h4><%= link_to(origami.title, origami_path(origami.id))%></h4>
                <div class="polaroid">
                    <img src="<%= origami.finished_image_url %>" alt="<%= origami.title%>" style="width:100px;height:100px;">
                </div>
                <br>
                <h6><%= link_to("Remove 🗑", "/origamis/#{origami.id}/delete_from_basket", method: :delete,  params: { origami_id: origami.id })%></h6>
                <br>
            <%end%>
    </div>
    <div class="basket-info-container">
        <h3>Recommended pattern based your basket:</h3>
        <h4><%= link_to(@recommended.title, origami_path(@recommended.id))%></h4>
        <div class="polaroid">
            <img src="<%= @recommended.finished_image_url %>" alt="<%= @recommended.title%>" style="width:100px;height:100px;">
        </div>
    </div>

        <%else%>
        <div class="basket-info-container">
            <p>--Your basket is empty. <%=link_to("Add some?", origamis_path)%> </p>
        </div>
        <%end%>
    
</ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<div>
<nav>

<div class="nav-left-edge-container">
    <div class="nav-bar-headers-background">
        <h1 class="page-header">∵ Sekkei ∴</h1>
    </div>
</div>


<h4 class="nav-bar-headers">
    <div class="nav-bar-headers-background">
        <%= link_to("Origamis", origamis_path)%> //
        <%= link_to("Posts", posts_path) %> //
        <%= link_to("Origami Search", origamis_search_path) %> 
    </div>
</h4>


<div class="nav-right-edge-container">
<h4 class="nav-links-right">
    <div class="nav-bar-headers-background">
        <% if @logged_in_user %>
            Welcome, <%= link_to(@logged_in_user.name, user_path(@logged_in_user.id)) %>!
             ┊ <%= link_to("🛒", my_basket_path) %>
             ┊ <%= link_to("Logout", logout_path, :method => 'delete') %>
        <% else %>
            <%= link_to("Login", login_path) %>
        <%end%>
    </div>
</h4>
</div>

</nav>
</div>
</head>
<body style="background-color:#ffe6e6">
    <%= yield %>
</body>
  
</html>

app/views/origamis/index.erb
<div class="origami-index-container">
    <div class="header-container">
        <h1>Origamis</h1>
    </div>
</div>

<div class="origami-show-container">

    <div class="origami-list-container">
    <% @origamis.each do |origami| %>
        <div class="origami-item-container">
            <div class="origami-list-polaroid polaroid">
            <h3><%= link_to(origami.title, origami_path(origami)) %></h3>
            <img src="<%= origami.finished_image_url %>" alt="<%= origami.title%>" style="width:200px;height:200px;">
            </div>
        </div>
    <% end %>
    </div>

 </div>

app/views/origamis/search.html.erb
<div class="origami-search-container">
    <div class="header-container">

      <h2>⋰ Search for origami ⋱</h2>

    </div>

    <div class="origami-info">

      <%= form_tag(origamis_search_results_path, :method => "get") do %>  
        <h3><%= label_tag(:title, "Search by title:") %></h3>
        <%= select_tag(:title, options_for_select(@origami_titles), {prompt: "title..."})%>

        <h3> <%= label_tag(:category, "Search by category:") %></h3>
        <%= select_tag(:category, options_for_select(@origami_categories, " "), {prompt: "category..."}) %>

        <h3><%= label_tag(:difficulty, "Search by difficulty:") %></h3>
        <%= select_tag(:difficulty, options_for_select(@origami_difficulties, " "), {prompt: "difficulty..."}) %></h3>
        
        <h3><%= submit_tag("Search") %>
        
      <% end %>
      </div>

      </div>

app/views/origamis/show.erb
<div class="origami-search-container">
    <div class="header-container">
        <h2><%=@origami.title%></h2>

        <% if (@logged_in_user && !@logged_in_user.basket_origamis.include?(@origami))%>
            <%= button_to("Add to Basket", add_to_basket_path, method: :post,  params: { origami_id: @origami.id })%>
        <% elsif (@logged_in_user && @logged_in_user.basket_origamis.include?(@origami))%>
            <%= button_to("Remove From Basket", delete_from_basket_path, method: :delete,  params: { origami_id: @origami.id })%>
        <%end%>
        <br>

        <div class="polaroid">
            <img src="<%= @origami.finished_image_url %>" alt="<%= @origami.title%>" style="width:200px;height:200px;">
        </div>

        <h3><%=@origami.category%> // <%=@origami.style%> // Difficulty [<%=' ◍ ' * @origami.difficulty%>]</h3>
 

    </div>
</div>
<div class="origami-show-container">

    <div class="origami-info">
        <h4>Description:</h4>
        <p><%=@origami.description%></p>
    </div>

    <div class="origami-info">
        <h3>Folding Diagram:</h3>
        <iframe src="<%= @origami.instruction_image_url %>" alt="Instructions" height="1150" width="800"></iframe>
    </div>
</div>

app/views/posts/_form.erb
<% if flash[:errors] %>
    <div class="post-info-container">
    <% flash[:errors].each do |error| %>
      <p style="font-weight: bold">
        <%= error %>
      </p>
    <% end %>
  </div>
<% end %>

<div class="post-info-container">

<%= form_for @post do |f| %>
    <p><%= f.label :title%></p>
    <%= f.text_field :title %>

    <p><%= f.label :content%> </p>
     <%= f.text_area :content %>

    <p><%= f.label :origami_id %></p>
    <%= f.collection_select :origami_id, @origamis, :id, :title %>
    <br>

    <%f.hidden_field :user_id, value: @logged_in_user.id%>

    <%= f.submit %>
<% end %>

</div>

app/views/posts/index.erb
 <div class="post-header-container">
    <div class="post-info-container">
        <h2>Posts</h2>
    </div>
</div>
<br>

<div class="post-show-container">
    <% if @logged_in_user%>
      <div class="create-post-link-background">
        <%= link_to("Create a post", new_post_path)%>
      </div>
    <%end%>
</div>
        
    <br>
     <% @posts.each do |post|%>
        <div class="post-show-container">
        <div class="header-container">
            <h2> <%= link_to(post.title, post_path(post))%></h2>
            <h5>Folder: <%=link_to(post.user.username, user_path(post.user.id))%></h5>
        </div>
        </div>
    <% end %>

app/views/posts/new.html.erb
<div class="post-show-container">
    <div class="post-info-container">

    <h3>Create a New Post</h3>

    </div>

    <%= render "form" %>

app/views/posts/show.erb
<div class="post-show-container">

    <div class="header-container">
        <h2><%= @post.title %></h2>
        <h5>Folder: <%=link_to(@post.user.username, user_path(@post.user.id))%></h5>
    </div>

    <div class="post-info-container">
        <p><%=@post.content%></p>
    </div>
</div>

app/views/users/_form.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |message| %>
        <p style="color: red;"> <%= message %> </p>
    <% end%>

<% end%>

<%= form_for @user do |f| %>
    <%= f.label :name%>
    <%= f.text_field :name%>

    <%= f.label :username%> 
    <%= f.text_field :username%>

    <%= f.label :password%> 
    <%= f.text_field :password%>

    <%= f.label :bio%> 
    <%= f.text_field :bio%>

    <%= f.submit %>
<% end %>

app/views/users/login.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p style="color: red;">
      <%= error %>
    </p>
  <% end %>
<% end %>

<div class="user-show-container">
    <div class="user-info-container">

      <h2>Login</h2>

      <%= form_for :session, url: create_login_session_path do |f| %>
        <h5><%= f.label :username %></h5>
        <%= f.text_field :username %>

        <h5><%= f.label :password %></h5>
        <%= f.password_field :password %>
        <br>
        <br>
        <%= f.submit("Login")%>
      <% end %>
    </div>


  <h5>Don't have an account yet? Why not <%=link_to("sign up?", new_user_path)%></h5>

</div>

app/views/users/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p style="weight: bold;">
      <%= error %>
    </p>
  <% end %>
<% end %>

<h1>Sign Up!</h1>

<%= form_for @user do |f| %>
  <h4><%= f.label :name %></h4>
  <%= f.text_field :name %>

  <h4><%= f.label :username %></h4>
  <%= f.text_field :username %>

  <h4><%= f.label :bio %></h4>
  <%= f.text_area :bio %>

  <h4><%= f.label :password %></h4>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>

app/views/users/show.erb
<div class="user-show-container">
    <div class="header-container">
    
        <h2> <%=@user.name%> </h3>
        <h3> <i>username </i> // <%=@user.username%> </h4>
    </div>

    <div class="user-info-container">
        <h3>Bio: </h3> <p><%=@user.bio%></p>
    </div>

    <div class="user-info-container">
        <h3>Posts:</h3>
        <%if @posts.length > 0%>
            <%@posts.each do |post|%>
                <h4><%= link_to(post.title, post_path(post.id))%></h4>
            <%end%>
        <%else%>
            <p>--This user has yet to write any posts.</p>
        <%end%>
    </div>
</div>